# Библиотека NumPy


NumPy - векторные/научные вычисления. Пакет содержит функциональные средства для работы с многомерными массивами и высокоуровневыми математическими функциями.

Справочные материалы по numpy: https://pythonworld.ru/numpy

In [13]:
import numpy as np # Подключаем библиотеку numpy и задаем ей псевдоним np

### 1. Структура np.ndarray




np.ndarray - это массив, содержащий элементы **одного типа**. 

Давайте посмотрим, что это значит:

In [14]:
my_list1 = [2, 4, 5] # Создаем переменную my_list1 и записываем в нее список из трех значений
print (my_list1) # Выводим на экран созданный список
print (type(my_list1)) # Выводим на экран тип переменной my_list1

[2, 4, 5]
<class 'list'>


In [15]:
my_numpy1 = np.array(my_list1) # Создаем numpy-массив из списка my_list1
print(my_numpy1) # Выводим на экран созданный numpy-массив
print(type(my_numpy1)) # Выводим на экран тип переменной my_numpy1
print(my_numpy1.dtype) # Выводим на экран тип элементов массива my_numpy1

[2 4 5]
<class 'numpy.ndarray'>
int32


In [16]:
my_list2 = [2, 3.14] # Создаем переменную my_list_float и записываем в нее список из двух значений (типа int и типа float)
my_numpy2 = np.array(my_list2) #  Создаем numpy-массив из списка my_list2
print(my_numpy2.dtype)  # Выводим на экран тип элементов массива my_numpy2

float64


In [17]:
print(my_list2) # Выводим на экран созданный список my_list2
print(my_numpy2) # Выводим на экран созданный массив my_numpy2

[2, 3.14]
[2.   3.14]


In [18]:
my_list3 = [2, 3.14, 'text data'] # Создаем переменную my_list2 и записываем в нее список из трех значений (типа int, типа float и типа str)
my_numpy3 = np.array(my_list3) # Создаем numpy-массив из списка my_list3
print(my_list3) # Выводим на экран созданный список my_list3
print(my_numpy3) # Выводим на экран созданный массив my_numpy3
print(my_numpy3.dtype) # Выводим на экран тип элементов массва my_numpy3

[2, 3.14, 'text data']
['2' '3.14' 'text data']
<U32


In [19]:
my_list4 = [2, 3.14, 'text data', [2,3,4]] # Создаем переменную my_list4 и записываем в нее список из четырех значений (типа int, типа float, типа str  и список)
print(my_list4) # Выводим на экран созданный список my_list4

[2, 3.14, 'text data', [2, 3, 4]]


In [20]:
my_numpy4 = np.array(my_list4) # Создаем numpy-массив из списка my_list3
print(my_numpy4) # Выводим на экран созданный массив my_numpy4
print(my_numpy4.dtype) # Выводим на экран тип элементов массива my_numpy4

[2 3.14 'text data' list([2, 3, 4])]
object


C:\Users\hohlo\AppData\Local\Temp\ipykernel_23044\3971614367.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  my_numpy4 = np.array(my_list4) # Создаем numpy-массив из списка my_list3


In [21]:
my_numpy5 = np.array([2, 3.14, 'text data', [2, 4, 5]], dtype='object') # Создаем numpy-массив из списка и указываем тип элементов - 'object'
print(my_numpy5) # Выводим на экран созданный массив my_numpy5
print(my_numpy5.dtype) # Выводим на экран тип элементов массива my_numpy5

[2 3.14 'text data' list([2, 4, 5])]
object


In [22]:
my_numpy6 = np.array([2, 3.14, 'text data', [2, 4, 5]], dtype='int64') # Создаем numpy-массив из списка и указываем тип элементов - 'int'

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [23]:
my_numpy7 = np.array([2, 3.14], dtype='int64') # Создаем numpy-массив из списка и указываем тип элементов - 'int'
print(my_numpy7) # Выводим на экран созданный массив my_numpy5
print(my_numpy7.dtype) # Выводим на экран тип элементов массива my_numpy5

[2 3]
int64


### 2. Типы данных


В NumPy реализованы свои типы данных, которые отличаются от встроенных в Python.

Подробнее о типах: https://docs.scipy.org/doc/numpy/user/basics.types.html

Например, встроенный тип int ничем не ограничен (кроме вашей памяти). Целые числа в numpy имеют фиксированный размер: np.int8, np.int16...

Другое различие кроется во встроенных методах:

In [24]:
value = -167 # Создаем переменную value и записываем в нее значение
numpy_value = np.uint8(value) # Преобразуем переменную value к типу np.uint8

In [25]:
print(value) # Выводим на экран значение переменной value

-167


In [26]:
print(numpy_value) # Выводим на экран значение переменной numpy_value

89


In [27]:
print(type(value)) # Выводим на экран тип переменной value

<class 'int'>


In [28]:
print(type(numpy_value)) # Выводим на экран тип переменной numpy_value

<class 'numpy.uint8'>


### 3. Одномерные массивы

#### Одномерные numpy массивы


In [29]:
numpy_digital = np.array([1, 2, 3, 4, 5]) # Создаем numpy-массив из списка цифр

In [30]:
numpy_str = np.array(['cat', 'mouse', 'dog', 'rat']) # Создаем numpy-массив из списка слов 

In [31]:
print(numpy_digital.dtype) # Выводим на экран тип элементов массива numpy_digital

int32


In [32]:
print(numpy_str.dtype) # Выводим на экран тип элементов массива numpy_str

<U5


In [33]:
print(numpy_digital.shape) # Выводим на экран размерность массива numpy_digital

(5,)


In [34]:
print(numpy_str.shape) # Выводим на экран размерность массива numpy_str

(4,)


In [35]:
print(numpy_digital.size) # Выводим на экран количество элементов массива numpy_digital

5


In [36]:
numpy_digital2 = np.array([1, 2, 3, 4, 5, 6]) # Создаем numpy-массив из списка цифр
print(numpy_digital2) # Выводим на экран массив numpy_digital
print(numpy_digital2.shape) # Выводим на экран размерность массива numpy_digital

[1 2 3 4 5 6]
(6,)


In [37]:
numpy_new = numpy_digital2.reshape((3, 2)) # Изменяем размерность массива numpy_digital2 из (6,) -> (3, 2)
print(numpy_new) # Выводим на экран массив numpy_new
print(numpy_new.shape) # Выводим на экран размерность массива numpy_new
print(numpy_new.size) # Выводим на экран количество элементов массива numpy_new

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
6


In [38]:
numpy_new2 = numpy_digital2.reshape((2, 3)) # Изменяем размерность массива numpy_digital2 из (6,) -> (2, 3)
print(numpy_new2) # Выводим на экран массив numpy_new2
print(numpy_new2.shape) # Выводим на экран размерность массива numpy_new2
print(numpy_new2.size) # Выводим на экран количество элементов массива numpy_new2

[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [39]:
numpy_new3 = numpy_digital2.reshape((1, 6)) # Изменяем размерность массива numpy_digital2 из (6,) -> (1, 6)
print(numpy_new3) # Выводим на экран массив numpy_new3
print(numpy_new3.shape) # Выводим на экран размерность массива numpy_new3
print(numpy_new3.size) # Выводим на экран количество элементов массива numpy_new3

[[1 2 3 4 5 6]]
(1, 6)
6


In [40]:
print(numpy_digital2) # Выводим на экран массив numpy_new
print(numpy_digital2.shape) # Выводим на экран размерность массива numpy_new
print(numpy_digital2.size) # Выводим на экран количество элементов массива numpy_new

[1 2 3 4 5 6]
(6,)
6


In [41]:
print(numpy_digital) # Выводим на экран массив numpy_new
print(numpy_digital.shape) # Выводим на экран размерность массива numpy_digital

[1 2 3 4 5]
(5,)


In [42]:
numpy_new4 = numpy_digital.reshape((2, 3)) # Изменяем размерность массива numpy_digital из (5,) -> (2, 3)

ValueError: cannot reshape array of size 5 into shape (2,3)

#### Индексация




In [43]:
numpy_new5 = np.array([102,123,33,54,25,136]) # Создаем numpy-массив из списка цифр
print(numpy_new5) # Выводим на экран массив numpy_new5

[102 123  33  54  25 136]


In [44]:
print(numpy_new5[0]) # Выводим на экран нулевой элемент массива numpy_new5

102


In [45]:
print(numpy_new5[1]) # Выводим на экран первый элемент массива numpy_new5

123


In [46]:
print(numpy_new5[-1]) # Выводим на экран последний (минус первый) элемент массива numpy_new5

136


In [47]:
print(numpy_new5[:]) # Выводим на экран все элементы массива numpy_new5

[102 123  33  54  25 136]


In [48]:
print(numpy_new5[1:]) # Выводим на экран все элементы массива numpy_new5, начиная с первого

[123  33  54  25 136]


In [49]:
print(numpy_new5[:3]) # Выводим на экран с нулевого по третий элементы массива numpy_new5

[102 123  33]


In [50]:
print(numpy_new5[-2:]) # Выводим на экран все элементы массива numpy_new5, начиная с предпоследнего

[ 25 136]


In [51]:
print(numpy_new5[1:4]) # Выводим на экран с первого по четвертый элемент массива numpy_new5

[123  33  54]


In [52]:

print(numpy_new5 > 55) # Выводим маску массива numpy_new5 для условия: значение элемента больше 55

[ True  True False False False  True]


In [53]:
print(numpy_new5[(numpy_new5 > 25) & (numpy_new5 < 67)]) # Производим подвыборку элементов массива, значения которых больше 25 и меньше 67

[33 54]


In [54]:
arr1 = np.array([2, 3, 12]) # Создаем numpy-массива из списка
arr2 = np.array([i for i in range(7)]) # Создаем numpy-массив с помощью генератора цикла

print(arr1) # Выводим массив arr1
print(arr2) # Выводим массив arr2

[ 2  3 12]
[0 1 2 3 4 5 6]


In [55]:
mask = np.array([(i in arr2) for i in arr1]) # Создаем маску для массива arr1 по наличию элемента в массиве arr2

print(mask) # Выводим маску 

[ True  True False]


In [56]:
arr1[mask]

array([2, 3])

#### Встроенные методы


чтобы увидеть все доступные методы, после точки нажмите "Tab"

In [57]:
numpy_array = np.array([1,2,3,4,5,6,7,8,9,10]) # Создаем numpy-массив из целых чисел
print(numpy_array) # Выводим на экран массив numpu_array

[ 1  2  3  4  5  6  7  8  9 10]


In [58]:
print(numpy_array.sum()) # Выводим на экран сумму всех элементов массива numpy_array

55


In [59]:
print(numpy_array.mean()) # Выводим на экран среднее значение всех элементов массива numpy_array

5.5


In [60]:
print(numpy_array.max()) # Выводим на экран максимальный элемент массива numpy_array

10


In [61]:
print(numpy_array.min()) # Выводим на экран минимальный элемент массива numpy_array

1


In [62]:
print(numpy_array.prod()) # Выводим на экран произведение всех элементов массива numpy_array

3628800


In [63]:
str_array = np.array(['Один', 'Два','Три','Четыре']) # Создаем numpy-массив из четырех строковых значений
print(str_array) # Выводим на экран массив str_array

['Один' 'Два' 'Три' 'Четыре']


In [64]:
str_array.sort() # Сортируем массив str_array
print(str_array) # Выводим на экран массив str_array

['Два' 'Один' 'Три' 'Четыре']


In [65]:
my_type = [('city', '<U32'), ('region', np.int32)] # Создадим список, где укажем тип данных будущего массива
values = [('Москва', 99), ('Пенза', 58), ('Рязань', 62)] # Создадим список со значениями будущего массива
regions = np.array(values, dtype=my_type) # Создаем numpy-массива из указанных значений и задаем тип данных для каждого столбца
print(regions) # Выводим на экрам массив regions

[('Москва', 99) ('Пенза', 58) ('Рязань', 62)]


In [66]:
regions['city'] # Обращаемся к столбцу массива по заданному имени

array(['Москва', 'Пенза', 'Рязань'], dtype='<U32')

In [67]:
%%timeit
numpy_array.sum() # Считаем сумму элементов массива numpy_array и смотрим на время выполнения операции с помощью магической команды timeit

1.74 µs ± 115 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [68]:
            
    %%timeit
numpy_array.mean() # Считаем среднее значение элементов массива numpy_array и смотрим на время выполнения операции с помощью магической команды timeit

6.53 µs ± 171 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [69]:
%%timeit
numpy_array.sum()
numpy_array.mean()

9.1 µs ± 393 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
# Задаем параметры 
## n - кол-во циклов повторений
## r - кол-во повторений в одном цикле

In [ ]:
%%timeit -n 5 -r 10
numpy_array.sum()

#### Операции с массивами



In [70]:
numpy_10 = np.arange(5) # Создаем numpy-массив из последовательности элементов от 0 до 4 (5 не включается)
print(numpy_10) # Выводим на экран массив numpy_10

[0 1 2 3 4]


In [71]:
numpy_11 = np.arange(3, 6) # Создаем numpy-массив из последовательности элементов от 3 до 5 (6 не включается)
print(numpy_11) # Выводим на экран массив numpy_11

[3 4 5]


In [72]:
numpy_12 = np.arange(3, 16, 4) # Создаем numpy-массив из последовательности элементов от 3 до 15 с шагом 4
print(numpy_12) # Выводим на экран массив numpy_12

[ 3  7 11 15]


#### Векторные операции



In [73]:
my_list1 = [0,1,2,3,4,5] # Создаем список из 5 элементов
my_list2 = [6,7,8,9,10,11] # Создаем еще один список также из 5 элементов
my_numpy1 = np.array(my_list1) # Создаем массив из списка my_list1
my_numpy2 = np.array(my_list2) # Создаем массив из списка my_list2
print(my_list1 + my_list2) # Выводим результат сложения двух списков
print(my_numpy1 + my_numpy2) # Выводим результат сложения двух массивов

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[ 6  8 10 12 14 16]


In [74]:
print(my_numpy1 - my_numpy2) # Выводим разность двух массивов

[-6 -6 -6 -6 -6 -6]


In [75]:
print(my_list1 - my_list2) # Выводим рвзность двух списков

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [76]:
print(my_numpy1 / my_numpy2) # Выводим частное двух массивов

[0.         0.14285714 0.25       0.33333333 0.4        0.45454545]


In [77]:
# обратите внимание, что python нормально обработал деление на ноль
## inf - infinite value, бесконочность
print(my_numpy2 / my_numpy1) # Выводим частное двух массивов

[inf 7.  4.  3.  2.5 2.2]


C:\Users\hohlo\AppData\Local\Temp\ipykernel_23044\1919026743.py:3: RuntimeWarning: divide by zero encountered in divide
  print(my_numpy2 / my_numpy1) # Выводим частное двух массивов


In [78]:
print(my_numpy1 * my_numpy2) # поэлементное умножение двух массивов

[ 0  7 16 27 40 55]


In [79]:
print(my_numpy1 ** my_numpy2) # поэлементное возведение в степень

[       0        1      256    19683  1048576 48828125]


In [80]:
# методы работают и без создания новой переменной, но нужны скобочки ()
print(((my_numpy1 * my_numpy2 - my_numpy1) ** 2).sum()) # Выведем сумму элементов "составного" массива

4604


In [81]:
print(my_numpy1 * 5 + my_numpy2[0] * 17)

[102 107 112 117 122 127]


### 4. Многомерные массивы


2D - матрица

3D, ..., nD - тензоры

In [82]:
# создаем двумерный массив
my_2d_array = np.array([[3, 6, 2, 7],
                        [9, 2, 4, 8],
                        [8, 2, 3, 6]])

print(my_2d_array)

[[3 6 2 7]
 [9 2 4 8]
 [8 2 3 6]]


In [83]:
# создаем трехмерный массив
my_3d_array = np.array([[[3, 6, 2, 7],
                        [9, 2, 4, 8],
                        [8, 2, 3, 6]]])

print(my_3d_array)

[[[3 6 2 7]
  [9 2 4 8]
  [8 2 3 6]]]


In [84]:
print(my_2d_array.shape) # Выводим на экран размерность массива my_2d_array
print(my_3d_array.shape) # Выводим на экран размерность массива my_3d_array

(3, 4)
(1, 3, 4)


In [85]:
# кол-во элементов массива
print(my_2d_array.size) # Выводим на экран количество элементов массива my_2d_array
print(my_3d_array.size) # Выводим на экран количество элементов массива my_3d_array

12
12


#### Индексация


построчно

In [86]:
# Создадим двумерный массив
my_2d_array2 = np.array([[3, 6, 2, 7],
                        [9, 2, 4, 8],
                        [8, 2, 3, 6]])

print(my_2d_array2) # Выведем на экран массив my_2d_array2

[[3 6 2 7]
 [9 2 4 8]
 [8 2 3 6]]


In [87]:
print(my_2d_array2[0]) # Выведем на экран нулевую строку

[3 6 2 7]


In [88]:
# первая строка
print(my_2d_array2[1]) # Выведем на экран первую строку
print(my_2d_array2[-1]) # Выведем на экран последнюю строку

[9 2 4 8]
[8 2 3 6]


поэлементно

In [89]:
print(my_2d_array2) # Выведем на экран массив my_2d_array2

[[3 6 2 7]
 [9 2 4 8]
 [8 2 3 6]]


In [90]:
print(my_2d_array2[0,0]) # Выведем на экран элемент с индексом [0,0] (нулевая строка, нулевой столбец)

3


In [91]:
print(my_2d_array2[0,1]) # Выведем на экран элемент с индексом [0,1] (нулевая строка, первый столбец)

6


In [92]:
print(my_2d_array2[1,2]) # Выведем на экран элемент с индексом [1,2] (первая строка, второй столбец)

4


по столбцам

In [93]:
print(my_2d_array2[:, 0]) # Выведем на экран нулевой столбец

[3 9 8]


In [94]:
print(my_2d_array2[:, 1]) # Выведем на экран первый столбец

[6 2 2]


In [95]:
print(my_2d_array2[1:, 1]) # Выведем на экран первый столбец  и все элементы этого столбца, начиная с первого

[2 2]


#### Операции с двумерными массивами и встроенные методы




In [96]:
    print(my_2d_array2) # Выведем на экран массив my_2d_array2

[[3 6 2 7]
 [9 2 4 8]
 [8 2 3 6]]


In [97]:
print(my_2d_array2.sum()) # Выводим сумму элементов двумерного массива

60


In [98]:
print(my_2d_array2.min(axis=1)) # Выводим минимальный элемент в каждой строке

[2 2 2]


In [99]:
print(my_2d_array2.sum(axis=0)) # Выводим сумму каждого столбеца

[20 10  9 21]


In [100]:
# np.ones_like создает массив из единиц такой же размерности как и массив а
new_2d_array = np.ones_like(my_2d_array2) # Создаем массив той же размерности, что и my_2d_array2 и заполняем его единицами
print(new_2d_array) # Выводим на экран массив new_2d_кarray

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [101]:
new_2d_array2 = np.zeros((5,3)) # Создаем массив из нулей заданной размерности (5,3)
print (new_2d_array2) # Выводи на экран массив new_2d_array2

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [102]:
new_2d_array2 = new_2d_array * 2 # Умножим каждый элемент массива на 2
print(new_2d_array2) # Выводим на экран массив new_2d_array2

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [103]:
print(new_2d_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [104]:
# поэлементное умножение двух массивов
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[4,3,2],
                 [6,4,3]])
print(arr1 * arr2) # Выведем на экран результат поэлементого умножения массивов

[[ 4  6  6]
 [24 20 18]]


#### Структура np.matrix


Подробнее: https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html

In [105]:
my_matrix = np.matrix(arr1) # Создадим матрицу из массива arr1
print(my_matrix) # Выведем на экран матрицу my_matrix
print(type(arr1)) # Выведем на экран тип переменной arr1
print(type(my_matrix)) # Выведем на экран тип переменной my_matrix

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
<class 'numpy.matrix'>


In [106]:
print(my_matrix.T) # Выведем на экран транспонированную матрицу

[[1 4]
 [2 5]
 [3 6]]


In [107]:
# в случае с np.matrix выполняется матричное умножение, а не поэлементное (!!!)
print(my_matrix * my_matrix.T)


[[14 32]
 [32 77]]


#### Тензоры 



In [108]:
# создаем четыркхмерный массив из случайных значений размерности 2 на 3 на 4 на 5
my_tensor = np.random.random((2, 3, 4, 5))
print(my_tensor)

[[[[0.90164649 0.4999424  0.59482474 0.22401007 0.8072517 ]
   [0.07636958 0.93754102 0.60478191 0.59774864 0.90960937]
   [0.4632273  0.26123155 0.462418   0.3362733  0.53614597]
   [0.98798396 0.42844529 0.07946982 0.48087871 0.8109102 ]]

  [[0.80787863 0.06711415 0.74531173 0.57343473 0.44147693]
   [0.42629217 0.52202672 0.5688396  0.20887739 0.07240551]
   [0.66633701 0.96933531 0.8412048  0.12713567 0.34198681]
   [0.99991858 0.09227155 0.04395908 0.17235076 0.38123556]]

  [[0.49198013 0.50752366 0.15303152 0.72415228 0.94860734]
   [0.7006949  0.50088065 0.93496453 0.34405827 0.40456199]
   [0.84289353 0.00225234 0.15804094 0.54791706 0.67724936]
   [0.96316695 0.54132901 0.87519794 0.2913653  0.40914185]]]


 [[[0.39299396 0.59951572 0.82845583 0.52369149 0.1410601 ]
   [0.88165515 0.61863362 0.25016165 0.78871098 0.33698608]
   [0.26559871 0.04722685 0.37916419 0.45823972 0.39539978]
   [0.89201394 0.18286427 0.99807669 0.69749937 0.75737332]]

  [[0.15363137 0.88177004 0.42

In [109]:
# проверяем размерность
print(my_tensor.shape) # Выводим на экран размерность массива my_tensor

(2, 3, 4, 5)


Как поэлементно обращаться к тензорам?

In [110]:
# элемент с индексами 0 по всем осям
my_tensor[0, 0, 0, 0]

0.9016464925872826

In [111]:
# только первые строки
my_tensor[:,  :, :, 0]

array([[[0.90164649, 0.07636958, 0.4632273 , 0.98798396],
        [0.80787863, 0.42629217, 0.66633701, 0.99991858],
        [0.49198013, 0.7006949 , 0.84289353, 0.96316695]],

       [[0.39299396, 0.88165515, 0.26559871, 0.89201394],
        [0.15363137, 0.39589241, 0.44944586, 0.96752879],
        [0.73876297, 0.56626821, 0.29445168, 0.59173042]]])

In [112]:
# сумма элементов по второй оси
my_tensor.sum(axis=3)

array([[[3.02767541, 3.12605053, 2.05929613, 2.78768799],
        [2.63521617, 1.79844139, 2.9459996 , 1.68973553],
        [2.82529492, 2.88516034, 2.22835324, 3.08020105]],

       [[2.4857171 , 2.87614747, 1.54562923, 3.52782759],
        [2.51261049, 2.84916456, 3.44001035, 3.74487381],
        [3.41098242, 1.72489034, 2.69092755, 3.08838108]]])

### 5. Матричные операции


Умножение двух матриц

метод .dot

In [113]:
    print(arr1)

[[1 2 3]
 [4 5 6]]


In [114]:
print(arr2)

[[4 3 2]
 [6 4 3]]


In [115]:
# это не умножение(!!!)
## это поэлементное умножение
arr1 * arr2

array([[ 4,  6,  6],
       [24, 20, 18]])

In [116]:
# вот это умножение:
## метод .dot
arrT = arr1.T
arr3 = arrT.dot(arr2)
print(arr3)

[[28 19 14]
 [38 26 19]
 [48 33 24]]


### 6. Семплирование из распределений



Описание всех возможностей модуля np.random:

https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html


In [117]:
# создаем массив размера 5 на 5 со случайными числами из стандартного нормального распределения
rr = np.random.normal(0, 1, (5,5))
print(rr)

[[ 0.35729408  0.2731621  -0.58064499  0.40395534  0.14022823]
 [ 0.28253153  0.31138664 -0.85579179 -1.52897622  0.69014451]
 [-0.77618906  1.25105753 -1.12627861  1.76181978  2.87215685]
 [ 0.4873332   1.06261447 -0.8500319  -0.51453341 -0.01978035]
 [-0.81952552  1.59457961 -1.46780327 -0.30988788 -0.90431785]]


In [118]:
rr = np.random.randint(0, 10, (5,5))
print(rr)

[[6 8 0 5 1]
 [5 2 4 1 0]
 [9 6 5 2 2]
 [0 1 1 4 4]
 [3 4 5 9 3]]


In [119]:
rr = np.random.uniform(-4.33, 2.35, (4,4))
print(rr)

[[ 1.9527231  -4.24965846 -1.54503775  1.6131322 ]
 [ 0.9568285  -4.01421654 -2.23429534 -2.67795927]
 [ 1.42876684 -3.24120113 -2.20986728 -2.89583432]
 [-2.2935349  -1.23453219  0.48343221  0.66407898]]


### 7. Чтение файлов


In [ ]:
    #from google.colab import drive
#drive.mount('/content/drive')

In [122]:
# грузим массив из файла .csv
my_data = np.loadtxt('iris.csv', delimiter=',', skiprows=1) # skiprows=1 - пропускаем первую строку, поскольку в ней названия колонок базы 

In [123]:
# вот то, что мы подгрузили
print(my_data)

[[0.00e+00 5.10e+00 3.50e+00 1.40e+00 2.00e-01]
 [1.00e+00 4.90e+00 3.00e+00 1.40e+00 2.00e-01]
 [2.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [3.00e+00 4.60e+00 3.10e+00 1.50e+00 2.00e-01]
 [4.00e+00 5.00e+00 3.60e+00 1.40e+00 2.00e-01]
 [5.00e+00 5.40e+00 3.90e+00 1.70e+00 4.00e-01]
 [6.00e+00 4.60e+00 3.40e+00 1.40e+00 3.00e-01]
 [7.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01]
 [8.00e+00 4.40e+00 2.90e+00 1.40e+00 2.00e-01]
 [9.00e+00 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [1.00e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [1.10e+01 4.80e+00 3.40e+00 1.60e+00 2.00e-01]
 [1.20e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01]
 [1.30e+01 4.30e+00 3.00e+00 1.10e+00 1.00e-01]
 [1.40e+01 5.80e+00 4.00e+00 1.20e+00 2.00e-01]
 [1.50e+01 5.70e+00 4.40e+00 1.50e+00 4.00e-01]
 [1.60e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.70e+01 5.10e+00 3.50e+00 1.40e+00 3.00e-01]
 [1.80e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [1.90e+01 5.10e+00 3.80e+00 1.50e+00 3.00e-01]
 [2.00e+01 5.40e+00 3.40e+00 1.70e+00 2.

In [124]:
# массив имеет тип np.array сразу
type(my_data)

numpy.ndarray

In [125]:
# тип подгруженных данных - float64
my_data.dtype

dtype('float64')

In [126]:
my_data.shape

(150, 5)

# **Глоссарий**
array[n1:n2] - срез массива с элемента n1 по n2 (не включительно)

-----------------------

**Основные методы для ndarray **

.dtype - узнать тип данных массива

.shape - узнать размер массива

.reshape((*новый размер*))  - поменять размер массива

.sum() сумма всех элементов

.mean() среднее всех элементов

.min() минимальное значение массива

.max() максимальное значение

.prod() произведение всех элементов

-------------------

np.arange(n) - генерация массива со значениями от 0 до n (не включительно)

np.loadtxt(адрес расположения файла+параметры загрузки)


