### Numpy Лабораторная работа 1



### Задача 1


* Подгрузите массив с файла **iris.csv** и назовите этот массив my_array. 

* Создайте двумерный массив из случайных чисел той же размерности, что и my_array (раздел "Семплирование из распределений", потребуется использовать размерность массива my_array).

* Назовите его my_generated_array.

**Решение:**

In [7]:
from pprint import pprint
import numpy as np
from sklearn.datasets import load_iris


iris = load_iris()  # Подгружаем iris датасет из sklearn.
my_array = np.array(iris.data)

shape = my_array.shape
my_generated_array = np.random.rand(shape[0], shape[1])  # Создаём массив размерностью my_array

print("Iris датасет:\n", my_array)
print("\nСгенерированный массив:\n", my_generated_array)

Iris датасет:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.

### Задача 2


* Выполните поэлементное умножение my_array на my_generated_array (раздел "Векторные операции").

* Склейте массивы my_array, my_generated_array в один (могут помочь методы np.concatenate, np.vstack, np.hstack).

* Возьмите склеенный массив и разделите его на равные части (больше двух). Можно сделать вручную через циклы либо воспользоваться методом vsplit.

**Решение:**

In [12]:
print('Поэлементно умноженный массив:\n', my_array * my_generated_array)

glued_array = np.concatenate((my_array, my_generated_array), axis=0)  # axis=0 - склейка по строкам (добавление вниз).
print('\nСклеенный массив:\n', glued_array)

split_arrays = np.vsplit(glued_array, 4)
print('\nРазделённый массив:\n', split_arrays)

Поэлементно умноженный массив:
 [[3.53335940e+00 3.15297649e-01 8.98647434e-01 5.36447025e-02]
 [3.92837138e+00 4.15054212e-01 1.04246600e+00 3.47417467e-02]
 [3.18101607e+00 2.04417681e-01 1.03261319e+00 9.27562086e-02]
 [3.03129778e+00 1.13225723e+00 1.26787788e+00 8.41270211e-02]
 [4.55547759e+00 3.57893380e+00 1.13917674e-01 2.43566377e-02]
 [5.84840358e-01 1.19120111e+00 5.08911796e-01 3.30306762e-01]
 [2.14910265e-01 6.49744151e-01 7.74952768e-01 7.98738945e-02]
 [4.51659063e+00 3.27906971e+00 7.64183505e-02 4.28416617e-02]
 [3.36411901e-01 1.21883654e+00 1.01247086e+00 1.82700445e-01]
 [4.53194237e+00 1.52175181e+00 7.09197722e-01 2.74613481e-02]
 [3.58714877e-01 2.24394949e+00 2.75852998e-01 1.21117731e-01]
 [4.21956002e+00 2.12054901e+00 8.06356214e-01 1.69520110e-01]
 [2.65539839e-01 1.67850821e+00 9.23094362e-01 6.00821178e-02]
 [1.88606513e-01 1.08591006e+00 6.05150537e-01 3.15996341e-02]
 [4.84606942e+00 2.51497699e+00 5.95538190e-01 9.70082021e-02]
 [2.88929853e+00 2.3773

### Задача 3


* Найдите все элементы массива my_array, которые больше трех и меньше 5 одновременно. Используйте методологию подвыборки массива с условием (раздел "Индексация").

**Решение:**

In [14]:
print('Выборка из массива (3 < x < 5):\n', my_array[(my_array > 3) & (my_array < 5)])

Выборка из массива (3 < x < 5):
 [3.5 4.9 4.7 3.2 4.6 3.1 3.6 3.9 4.6 3.4 3.4 4.4 4.9 3.1 3.7 4.8 3.4 4.8
 4.3 4.  4.4 3.9 3.5 3.8 3.8 3.4 3.7 4.6 3.6 3.3 4.8 3.4 3.4 3.5 3.4 4.7
 3.2 4.8 3.1 3.4 4.1 4.2 4.9 3.1 3.2 3.5 4.9 3.6 4.4 3.4 3.5 4.5 4.4 3.2
 3.5 3.8 4.8 3.8 4.6 3.2 3.7 3.3 3.2 4.7 3.2 4.5 3.1 4.9 4.  4.6 4.5 3.3
 4.7 4.9 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 3.1 4.4 4.5 4.1 4.5 3.9 3.2 4.8
 4.  4.9 4.7 4.3 4.4 4.8 4.5 3.5 3.8 3.7 3.9 4.5 3.4 4.5 3.1 4.7 4.4 4.1
 4.  4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 4.1 3.3 4.9 4.5 3.6 3.2 3.2 3.8 3.2
 4.9 4.9 3.3 3.2 4.8 4.9 3.8 3.4 3.1 4.8 3.1 3.1 3.1 3.2 3.3 3.4]


### Задача 4


Создайте трехмерный массив размера 2 на 3 на 4, состоящий из случайных ВЕЩЕСТВЕННЫХ чисел от 15 до 37. Используйте встроенные методы библиотеки  np.random.

**Решение:**

In [15]:
my_3d_array = np.random.randint(15, 37, size=(2, 3, 4))

print('Массив вещественных чисел размерностью 2, 3, 4:\n', my_3d_array)

Массив вещественных чисел размерностью 2, 3, 4:
 [[[28 31 22 23]
  [32 26 21 32]
  [25 17 23 32]]

 [[21 36 33 25]
  [21 30 25 28]
  [24 28 30 31]]]


### Задача 5


Используя массив из предыдущей задачи, преобразуйте его в новый массив со следующими значениями:

    * "small", если значения меньше 20
    * "medium", если значения в промежутке [20, 30]
    * "large", если значения больше 30

**Решение:**

In [16]:
def apply_threshold(value):
    if value < 20:
        return "small"
    elif value >= 20 and value <= 30:
        return "medium"
    else:
        return "large"


mapped_3d_array = np.array([[[apply_threshold(value) for value in subrow] for subrow in row] for row in my_3d_array])

print('Размеченный массив:\n', mapped_3d_array)

Размеченный массив:
 [[['medium' 'large' 'medium' 'medium']
  ['large' 'medium' 'medium' 'large']
  ['medium' 'small' 'medium' 'large']]

 [['medium' 'large' 'large' 'medium']
  ['medium' 'medium' 'medium' 'medium']
  ['medium' 'medium' 'medium' 'large']]]
